server:
  port: 80
  servlet:
    context-path: /wxserver

wx:
  signature:
  timestamp:
  nonce:
  echostr:
  Token: rzk
  appid: wx9b012c8a72024068
  secret: 0546d6d0bd51348b77a9b831518688db

spring:
  redis:
    #超过时间
    timeout: 10000ms
    #地址
    host: 120.79.7.36
    #端口
    port: 6381
    #数据库
    database: 0
    password: rzkruizhukai123.
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 1024
        # 最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
    #哨兵模式
    sentinel:
      #主节点名称
      master: mymaster
      #节点
      nodes: 120.55.192.186:26381,120.55.192.186:26382,120.55.192.186:26383
